/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

#define RCC_BASE_ADDR 			0x40021000UL

#define RCC_CFGR_REG_OFFSET 	0x04UL

#define RCC_CFGR_REG_ADDR		(RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

#define RCC_AHBENR				(RCC_BASE_ADDR + 0x14)

#define GPIOA_BASE_ADDR			0x48000000

int main(void)
{
	uint32_t *pRccCfgrReg = (uint32_t*)	RCC_CFGR_REG_ADDR;

	/* 1. Configure the RCC_CFGR register MCO bit fields to select HSI as clock source */
	*pRccCfgrReg |= (0x8 << 24); /* set 24 bit position, clear 25 26 27 bit positions */
	*pRccCfgrReg |= (0x7 << 28); /* set 24 bit position, clear 25 26 27 bit positions */
	/* 2. Configure the peripheral clock for GPIOA peripheral */

	/* a) Enable the peripheral clock for GPIOA peripheral */
	uint32_t *pRCCAhbEnr = (uint32_t*)(RCC_AHBENR);
	*pRCCAhbEnr |= (1 << 17); /* Enable GPIOA peripheral clock */

	/* b) Configure the mode of GPIOA pin 8 as alternate function mode */
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~(0x3 << 16); /* clear */
	*pGPIOAModeReg |= (0x2 << 16);	/* set */

	/* c) Configure the alternate function register to set the mode 0 for PA8	 */
	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~(0xF << 0);
	for(;;);
}
